name: solace_messaging
releases:
- name: docker
  version: latest
- name: solace-vmr
  version: latest
- name: solace-messaging
  version: latest
stemcells:
- alias: default
  os: ubuntu-trusty
  version: '3468'
update:
  canaries: 1
  canary_watch_time: 30000-240000
  max_in_flight: 1
  update_watch_time: 30000-600000
stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3468.15"
instance_groups:
- name: Shared-VMR
  stemcell: default
  instances: 1
  vm_type: small-highmem
  memory: 6144
  azs:
  - z1
  - z2
  - z3
  networks:
  - name: default
  persistent_disk: 20480
  jobs:
  - name: docker
    release: docker
    consumes: {}
  - name: prepare_vmr
    release: solace-vmr
    consumes: {}
  - name: containers
    release: solace-vmr
    consumes: {}
    provides:
      vmr_instance: { as: shared_vmr_list }
  - name: vmr_agent
    release: solace-vmr
    consumes: {}
  - name: route_registrar
    release: solace-vmr
    consumes:
      nats_link:
        from: nats
        deployment: ((cf_deployment))
  - name: route_registrar_active
    release: solace-vmr
    consumes:
      nats_link:
        from: nats
        deployment: ((cf_deployment))
  properties:
    admin_password: ((vmr_admin_password))
    admin_user: admin
    application_access_auth_scheme:
      value: vmr_internal
    broker_hostname: solace-messaging.((system_domain))
    broker_password: ((solace_broker_password))
    broker_user: ((solace_broker_user))
    cf_api_host: api.((system_domain))
    cf_client_id: solace_router
    cf_client_secret: ((solace_router_client_secret))
    cf_organization: ((solace_broker_cf_organization))
    cf_space: ((solace_broker_cf_space))
    containers:
    - dockerfile: |2-
                  FROM solace-app:latest

                  RUN \
                    echo '#!/bin/bash' > /sbin/dhclient && \
                    echo 'exit 0' >> /sbin/dhclient && \
                    echo '3a:40:d5:42:f4:86' > /usr/sw/.nodeIdentifyingMacAddr && \
                    chmod +x /sbin/dhclient
      encrypted_vars:
      - DEBUG_USERNAME_ROOT_ENCRYPTEDPASSWORD=solace1
      env_vars:
      - NODE_TYPE=MESSAGE_ROUTING_NODE
      - SERVICE_SSH_PORT=2222
      - ALWAYS_DIE_ON_FAILURE=1
      - USERNAME_ADMIN_PASSWORD=((vmr_admin_password))
      - USERNAME_ADMIN_GLOBALACCESSLEVEL=admin
      image: solace-bosh
      memory: 4G
      memory_swap: 6G
      name: solace
      net: host
      privileged: true
      shm_size: 2G
      uts: host
      volumes:
      - /var/vcap/store/prepare_vmr/volumes/jail:/usr/sw/jail
      - /var/vcap/store/prepare_vmr/volumes/var:/usr/sw/var
      - /var/vcap/store/prepare_vmr/volumes/internalSpool:/usr/sw/internalSpool
      - /var/vcap/store/prepare_vmr/volumes/adbBackup:/usr/sw/adb
      - /var/vcap/store/prepare_vmr/volumes/adb:/usr/sw/internalSpool/softAdb
    edition: ((vmr_edition))
    heartbeat_rate: 15000
    ldap_config:
      value: disabled
    management_access_auth_scheme:
      value: vmr_internal
    pool_name: Shared-VMR
    semp_port: 8080
    semp_ssl_port: 943
    ssh_port: 2222
    starting_port: ((starting_port))
    syslog_config:
      value: disabled
    system_domain: ((system_domain))
    tcp_routes_config:
      selected_option:
        tcp_route_enabled: not_allowed
      value: disabled
    tcp_routes_enabled: disabled
    tls_config:
      value: disabled
    vmr_agent_port: 18080
- name: Community-VMR
  stemcell: default
  instances: 1
  vm_type: small-highmem
  memory: 6144
  azs:
  - z1
  - z2
  - z3
  networks:
  - name: default
  persistent_disk: 20480
  properties:
    admin_password: ((vmr_admin_password))
    admin_user: admin
    application_access_auth_scheme:
      value: vmr_internal
    broker_hostname: solace-messaging.((system_domain))
    broker_password: ((solace_broker_password))
    broker_user: ((solace_broker_user))
    cf_api_host: api.((system_domain))
    cf_client_id: solace_router
    cf_client_secret: ((solace_router_client_secret))
    cf_organization: ((solace_broker_cf_organization))
    cf_space: ((solace_broker_cf_space))
    containers:
    - dockerfile: |2-
                  FROM solace-app:latest

                  RUN \
                    echo '#!/bin/bash' > /sbin/dhclient && \
                    echo 'exit 0' >> /sbin/dhclient && \
                    echo '3a:40:d5:42:f4:86' > /usr/sw/.nodeIdentifyingMacAddr && \
                    chmod +x /sbin/dhclient
      encrypted_vars:
      - DEBUG_USERNAME_ROOT_ENCRYPTEDPASSWORD=solace1
      env_vars:
      - NODE_TYPE=MESSAGE_ROUTING_NODE
      - SERVICE_SSH_PORT=2222
      - ALWAYS_DIE_ON_FAILURE=1
      - USERNAME_ADMIN_PASSWORD=((vmr_admin_password))
      - USERNAME_ADMIN_GLOBALACCESSLEVEL=admin
      image: solace-bosh
      memory: 4G
      memory_swap: 6G
      name: solace
      net: host
      privileged: true
      shm_size: 2G
      uts: host
      volumes:
      - /var/vcap/store/prepare_vmr/volumes/jail:/usr/sw/jail
      - /var/vcap/store/prepare_vmr/volumes/var:/usr/sw/var
      - /var/vcap/store/prepare_vmr/volumes/internalSpool:/usr/sw/internalSpool
      - /var/vcap/store/prepare_vmr/volumes/adbBackup:/usr/sw/adb
      - /var/vcap/store/prepare_vmr/volumes/adb:/usr/sw/internalSpool/softAdb
    edition: ((vmr_edition))
    heartbeat_rate: 15000
    ldap_config:
      value: disabled
    management_access_auth_scheme:
      value: vmr_internal
    pool_name: Community-VMR
    semp_port: 8080
    semp_ssl_port: 943
    ssh_port: 2222
    starting_port: ((starting_port))
    syslog_config:
      value: disabled
    system_domain: ((system_domain))
    tcp_routes_config:
      selected_option:
        tcp_route_enabled: not_allowed
      value: disabled
    tcp_routes_enabled: disabled
    tls_config:
      value: disabled
    vmr_agent_port: 18080
  jobs:
  - name: docker
    release: docker
    consumes: {}
  - name: prepare_vmr
    release: solace-vmr
    consumes: {}
  - name: containers
    release: solace-vmr
    consumes: {}
    provides:
      vmr_instance: { as: community_vmr_list }
  - name: vmr_agent
    release: solace-vmr
    consumes: {}
  - name: route_registrar
    release: solace-vmr
    consumes:
      nats_link:
        from: nats
        deployment: ((cf_deployment))
  - name: route_registrar_active
    release: solace-vmr
    consumes:
      nats_link:
        from: nats
        deployment: ((cf_deployment))
- name: Large-HA-VMR
  stemcell: default
  instances: 0
  vm_type: small-highmem
  memory: 6144
  azs:
  - z1
  - z2
  - z3
  networks:
  - name: default
  persistent_disk: 20480
  jobs:
  - name: docker
    release: docker
    consumes: {}
  - name: prepare_vmr
    release: solace-vmr
    consumes: {}
  - name: containers
    release: solace-vmr
    consumes: {}
    provides:
      vmr_instance: { as: large_ha_vmr_list }
  - name: vmr_agent
    release: solace-vmr
    consumes: {}
  - name: route_registrar
    release: solace-vmr
    consumes:
      nats_link:
        from: nats
        deployment: ((cf_deployment))
  - name: route_registrar_active
    release: solace-vmr
    consumes:
      nats_link:
        from: nats
        deployment: ((cf_deployment))
  properties:
    admin_password: ((vmr_admin_password))
    admin_user: admin
    application_access_auth_scheme:
      value: vmr_internal
    broker_hostname: solace-messaging.((system_domain))
    broker_password: ((solace_broker_password))
    broker_user: ((solace_broker_user))
    cf_api_host: api.((system_domain))
    cf_client_id: solace_router
    cf_client_secret: ((solace_router_client_secret))
    cf_organization: ((solace_broker_cf_organization))
    cf_space: ((solace_broker_cf_space))
    containers:
    - dockerfile: |2-
                  FROM solace-app:latest

                  RUN \
                    echo '#!/bin/bash' > /sbin/dhclient && \
                    echo 'exit 0' >> /sbin/dhclient && \
                    echo '3a:40:d5:42:f4:86' > /usr/sw/.nodeIdentifyingMacAddr && \
                    chmod +x /sbin/dhclient
      encrypted_vars:
      - DEBUG_USERNAME_ROOT_ENCRYPTEDPASSWORD=solace1
      env_vars:
      - NODE_TYPE=MESSAGE_ROUTING_NODE
      - SERVICE_SSH_PORT=2222
      - ALWAYS_DIE_ON_FAILURE=1
      - USERNAME_ADMIN_PASSWORD=((vmr_admin_password))
      - USERNAME_ADMIN_GLOBALACCESSLEVEL=admin
      image: solace-bosh
      memory: 4G
      memory_swap: 6G
      name: solace
      net: host
      privileged: true
      shm_size: 2G
      uts: host
      volumes:
      - /var/vcap/store/prepare_vmr/volumes/jail:/usr/sw/jail
      - /var/vcap/store/prepare_vmr/volumes/var:/usr/sw/var
      - /var/vcap/store/prepare_vmr/volumes/internalSpool:/usr/sw/internalSpool
      - /var/vcap/store/prepare_vmr/volumes/adbBackup:/usr/sw/adb
      - /var/vcap/store/prepare_vmr/volumes/adb:/usr/sw/internalSpool/softAdb
    edition: ((vmr_edition))
    heartbeat_rate: 15000
    ldap_config:
      value: disabled
    management_access_auth_scheme:
      value: vmr_internal
    pool_name: Large-HA-VMR
    semp_port: 8080
    semp_ssl_port: 943
    ssh_port: 2222
    starting_port: ((starting_port))
    syslog_config:
      value: disabled
    system_domain: ((system_domain))
    tcp_routes_config:
      selected_option:
        tcp_route_enabled: not_allowed
      value: disabled
    tcp_routes_enabled: disabled
    tls_config:
      value: disabled
    vmr_agent_port: 18080
- name: Large-VMR
  stemcell: default
  instances: 0
  vm_type: small-highmem
  memory: 6144
  azs:
  - z1
  - z2
  - z3
  networks:
  - name: default
  persistent_disk: 20480
  jobs:
  - name: docker
    release: docker
    consumes: {}
  - name: prepare_vmr
    release: solace-vmr
    consumes: {}
  - name: containers
    release: solace-vmr
    consumes: {}
    provides:
      vmr_instance: { as: large_vmr_list }
  - name: vmr_agent
    release: solace-vmr
    consumes: {}
  - name: route_registrar
    release: solace-vmr
    consumes:
      nats_link:
        from: nats
        deployment: ((cf_deployment))
  - name: route_registrar_active
    release: solace-vmr
    consumes:
      nats_link:
        from: nats
        deployment: ((cf_deployment))
  properties:
    admin_password: ((vmr_admin_password))
    admin_user: admin
    application_access_auth_scheme:
      value: vmr_internal
    broker_hostname: solace-messaging.((system_domain))
    broker_password: ((solace_broker_password))
    broker_user: ((solace_broker_user))
    cf_api_host: api.((system_domain))
    cf_client_id: solace_router
    cf_client_secret: ((solace_router_client_secret))
    cf_organization: ((solace_broker_cf_organization))
    cf_space: ((solace_broker_cf_space))
    containers:
    - dockerfile: |2-
                  FROM solace-app:latest

                  RUN \
                    echo '#!/bin/bash' > /sbin/dhclient && \
                    echo 'exit 0' >> /sbin/dhclient && \
                    echo '3a:40:d5:42:f4:86' > /usr/sw/.nodeIdentifyingMacAddr && \
                    chmod +x /sbin/dhclient
      encrypted_vars:
      - DEBUG_USERNAME_ROOT_ENCRYPTEDPASSWORD=solace1
      env_vars:
      - NODE_TYPE=MESSAGE_ROUTING_NODE
      - SERVICE_SSH_PORT=2222
      - ALWAYS_DIE_ON_FAILURE=1
      - USERNAME_ADMIN_PASSWORD=((vmr_admin_password))
      - USERNAME_ADMIN_GLOBALACCESSLEVEL=admin
      image: solace-bosh
      memory: 4G
      memory_swap: 6G
      name: solace
      net: host
      privileged: true
      shm_size: 2G
      uts: host
      volumes:
      - /var/vcap/store/prepare_vmr/volumes/jail:/usr/sw/jail
      - /var/vcap/store/prepare_vmr/volumes/var:/usr/sw/var
      - /var/vcap/store/prepare_vmr/volumes/internalSpool:/usr/sw/internalSpool
      - /var/vcap/store/prepare_vmr/volumes/adbBackup:/usr/sw/adb
      - /var/vcap/store/prepare_vmr/volumes/adb:/usr/sw/internalSpool/softAdb
    edition: ((vmr_edition))
    heartbeat_rate: 15000
    ldap_config:
      value: disabled
    management_access_auth_scheme:
      value: vmr_internal
    pool_name: Large-VMR
    semp_port: 8080
    semp_ssl_port: 943
    ssh_port: 2222
    starting_port: ((starting_port))
    syslog_config:
      value: disabled
    system_domain: ((system_domain))
    tcp_routes_config:
      selected_option:
        tcp_route_enabled: not_allowed
      value: disabled
    tcp_routes_enabled: disabled
    tls_config:
      value: disabled
    vmr_agent_port: 18080
- name: Medium-HA-VMR
  stemcell: default
  instances: 0
  vm_type: small-highmem
  memory: 6144
  azs:
  - z1
  - z2
  - z3
  networks:
  - name: default
  persistent_disk: 20480
  jobs:
  - name: docker
    release: docker
    consumes: {}
  - name: prepare_vmr
    release: solace-vmr
    consumes: {}
  - name: containers
    release: solace-vmr
    consumes: {}
    provides:
      vmr_instance: { as: medium_ha_vmr_list }
  - name: vmr_agent
    release: solace-vmr
    consumes: {}
  - name: route_registrar
    release: solace-vmr
    consumes:
      nats_link:
        from: nats
        deployment: ((cf_deployment))
  - name: route_registrar_active
    release: solace-vmr
    consumes:
      nats_link:
        from: nats
        deployment: ((cf_deployment))
  properties:
    admin_password: ((vmr_admin_password))
    admin_user: admin
    application_access_auth_scheme:
      value: vmr_internal
    broker_hostname: solace-messaging.((system_domain))
    broker_password: ((solace_broker_password))
    broker_user: ((solace_broker_user))
    cf_api_host: api.((system_domain))
    cf_client_id: solace_router
    cf_client_secret: ((solace_router_client_secret))
    cf_organization: ((solace_broker_cf_organization))
    cf_space: ((solace_broker_cf_space))
    containers:
    - dockerfile: |2-
                  FROM solace-app:latest

                  RUN \
                    echo '#!/bin/bash' > /sbin/dhclient && \
                    echo 'exit 0' >> /sbin/dhclient && \
                    echo '3a:40:d5:42:f4:86' > /usr/sw/.nodeIdentifyingMacAddr && \
                    chmod +x /sbin/dhclient
      encrypted_vars:
      - DEBUG_USERNAME_ROOT_ENCRYPTEDPASSWORD=solace1
      env_vars:
      - NODE_TYPE=MESSAGE_ROUTING_NODE
      - SERVICE_SSH_PORT=2222
      - ALWAYS_DIE_ON_FAILURE=1
      - USERNAME_ADMIN_PASSWORD=((vmr_admin_password))
      - USERNAME_ADMIN_GLOBALACCESSLEVEL=admin
      image: solace-bosh
      memory: 4G
      memory_swap: 6G
      name: solace
      net: host
      privileged: true
      shm_size: 2G
      uts: host
      volumes:
      - /var/vcap/store/prepare_vmr/volumes/jail:/usr/sw/jail
      - /var/vcap/store/prepare_vmr/volumes/var:/usr/sw/var
      - /var/vcap/store/prepare_vmr/volumes/internalSpool:/usr/sw/internalSpool
      - /var/vcap/store/prepare_vmr/volumes/adbBackup:/usr/sw/adb
      - /var/vcap/store/prepare_vmr/volumes/adb:/usr/sw/internalSpool/softAdb
    edition: ((vmr_edition))
    heartbeat_rate: 15000
    ldap_config:
      value: disabled
    management_access_auth_scheme:
      value: vmr_internal
    pool_name: Medium-HA-VMR
    semp_port: 8080
    semp_ssl_port: 943
    ssh_port: 2222
    starting_port: ((starting_port))
    syslog_config:
      value: disabled
    system_domain: ((system_domain))
    tcp_routes_config:
      selected_option:
        tcp_route_enabled: not_allowed
      value: disabled
    tcp_routes_enabled: disabled
    tls_config:
      value: disabled
    vmr_agent_port: 18080
- name: deploy-all
  jobs:
  - name: deploy-all
    release: solace-messaging
    provides: {}
    consumes:
      solace_vmr_shared_vmr: { from: shared_vmr_list }
      solace_vmr_community_vmr: { from: community_vmr_list }
      solace_vmr_large_vmr: { from: large_vmr_list }
      solace_vmr_medium_ha_vmr: { from: medium_ha_vmr_list }
      solace_vmr_large_ha_vmr: { from: large_ha_vmr_list }
  instances: 1
  vm_type: minimal
  stemcell: default
  lifecycle: errand
  azs:
  - z1
  networks:
  - name: default
  properties:
    apply_open_security_group: ((apply_open_security_group))
    app_domains:
    - ((system_domain))
    application_access_auth_scheme:
      value: vmr_internal
    cf:
      admin_password: ((cf_admin_password))
      admin_user: admin
    domain: ((system_domain))
    ldap_config:
      value: disabled
    management_access_auth_scheme:
      value: vmr_internal
    org: ((solace_broker_cf_organization))
    security:
      password: ((solace_broker_password))
      user: ((solace_broker_user))
    solace_messaging:
      app_manifest:
        buildpack: java_buildpack_offline
        env:
          IS_ENTERPRISE_MODE: '((is_enterprise_mode))'
          JBP_CONFIG_CONTAINER_CERTIFICATE_TRUST_STORE: '{enabled: true}'
          SOLACE_LOAD_VERSION: ((solace_load_version))
          SOLACE_ROUTER_CLIENT_ID: solace_router
          SOLACE_ROUTER_CLIENT_SECRET: ((solace_router_client_secret))
        memory: 1024M
        path: ((solace_service_broker_jar))
      auto_services:
      - name: p-mysql
        plan: 100mb
      enable_global_access_to_plans: true
      password: ((solace_broker_password))
      user: ((solace_broker_user))
    space: ((solace_broker_cf_space))
    ssl:
      skip_cert_verify: true
    starting_port: ((starting_port))
    syslog_config:
      value: disabled
    tcp_routes_config:
      selected_option:
        tcp_route_enabled: not_allowed
      value: disabled
    tls_config:
      value: disabled
    vmr_admin_password: ((vmr_admin_password))
- name: delete-all
  instances: 1
  vm_type: minimal
  stemcell: default
  lifecycle: errand
  azs:
  - z1
  networks:
  - name: default
  properties:
    app_domains:
    - ((system_domain))
    application_access_auth_scheme:
      value: vmr_internal
    cf:
      admin_password: ((cf_admin_password))
      admin_user: admin
    domain: ((system_domain))
    ldap_config:
      value: disabled
    management_access_auth_scheme:
      value: vmr_internal
    org: ((solace_broker_cf_organization))
    security:
      password: ((solace_broker_password))
      user: ((solace_broker_user))
    solace_messaging:
      app_manifest:
        buildpack: java_buildpack_offline
        env:
          IS_ENTERPRISE_MODE: '((is_enterprise_mode))'
          JBP_CONFIG_CONTAINER_CERTIFICATE_TRUST_STORE: '{enabled: true}'
          SOLACE_LOAD_VERSION: ((solace_load_version))
          SOLACE_ROUTER_CLIENT_ID: solace_router
          SOLACE_ROUTER_CLIENT_SECRET: ((solace_router_client_secret))
        memory: 1024M
        path: ((solace_service_broker_jar)) 
      auto_services:
      - name: p-mysql
        plan: 100mb
      enable_global_access_to_plans: true
      password: ((solace_broker_password))
      user: ((solace_broker_user))
    space: ((solace_broker_cf_space))
    ssl:
      skip_cert_verify: true
    starting_port: ((starting_port))
    syslog_config:
      value: disabled
    tcp_routes_config:
      selected_option:
        tcp_route_enabled: not_allowed
      value: disabled
    tls_config:
      value: disabled
    vmr_admin_password: ((vmr_admin_password))
  jobs:
  - name: delete-all
    release: solace-messaging
    consumes:
      solace_vmr_shared_vmr: { from: shared_vmr_list }
      solace_vmr_community_vmr: { from: community_vmr_list }
      solace_vmr_large_vmr: { from: large_vmr_list }
      solace_vmr_medium_ha_vmr: { from: medium_ha_vmr_list }
      solace_vmr_large_ha_vmr: { from: large_ha_vmr_list }

variables:
- name: vmr_admin_password
  type: password
- name: solace_broker_password
  type: password
- name: solace_broker_user
  type: password
- name: solace_router_client_secret
  type: password
