name: (( merge ))
director_uuid: <%= `bosh status --uuid` %>

releases:
- name: docker
  version: latest
- name: solace-vmr
  version: latest

compilation:
  workers: 1
  network: test-network
  reuse_compilation_vms: true
  cloud_properties:
    name: random

update:
  canaries: (( merge))
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: (( merge ))

resource_pools:
- name: common-resource-pool
  network: test-network
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    name: random

networks:
- <<: (( merge ))

jobs:
- <<: (( merge ))
  templates:
  -  {name: docker, release: docker}
  -  {name: prepare_vmr, release: solace-vmr}
  -  {name: containers, release: solace-vmr}
  -  {name: vmr_agent, release: solace-vmr}
  persistent_disk: 20480
  resource_pool: common-resource-pool
  networks:
  - name: test-network
    static_ips:
      - <<: (( merge ))
  properties:
    <<: (( merge ))
    vmr_agent_port: 18080
    starting_port: 7000
    broker_user: 'solacedemo'
    broker_password: 'solacedemo'
    broker_hostname: 'solace-messaging.local.pcfdev.io'
    heartbeat_rate: 15000
    admin_password: 'admin'
    admin_user: 'admin'
    support_user: 'support'
    support_password: 'support'
    semp_port: 8080
    semp_ssl_port: 943
    ssh_port: 2222
    system_domain: 'local.pcfdev.io'
    containers:
      - name: solace
        image: solace-bosh
        memory: 4G
        <<: (( merge ))
        env_vars:
         - "NODE_TYPE=MESSAGE_ROUTING_NODE"
         - "SERVICE_SSH_PORT=2222"
         - "ALWAYS_DIE_ON_FAILURE=1"
         - "USERNAME_ADMIN_PASSWORD=admin"
         - "USERNAME_ADMIN_GLOBALACCESSLEVEL=admin"
        encrypted_vars:
         - "DEBUG_USERNAME_SUPPORT_ENCRYPTEDPASSWORD=support"
         - "DEBUG_USERNAME_ROOT_ENCRYPTEDPASSWORD=solace1"
        net: host
        shm_size: 2G
        privileged: true
        uts: host
        volumes:
        - /var/vcap/store/prepare_vmr/volumes/jail:/usr/sw/jail
        - /var/vcap/store/prepare_vmr/volumes/var:/usr/sw/var
        - /var/vcap/store/prepare_vmr/volumes/internalSpool:/usr/sw/internalSpool
        - /var/vcap/store/prepare_vmr/volumes/adbBackup:/usr/sw/adb
        - /var/vcap/store/prepare_vmr/volumes/adb:/usr/sw/internalSpool/softAdb
- name: UpdateServiceBroker
  templates:
  -  {name: update_config, release: solace-vmr}
  persistent_disk: 4096
  instances: 1
  resource_pool: common-resource-pool
  networks:
  - name: test-network
    static_ips:
      - 10.244.0.2
  properties:
    vmr_agent_port: 18080
    starting_port: 7000
    broker_user: 'solacedemo'
    broker_password: 'solacedemo'
    broker_hostname: 'solace-messaging.local.pcfdev.io'
    heartbeat_rate: 15000
    admin_password: 'admin'
    admin_user: 'admin'
    support_user: 'support'
    support_password: 'support'
    semp_port: 8080
    semp_ssl_port: 943
    system_domain: 'local.pcfdev.io'
    ssh_port: 2222
    <<: (( merge ))
